//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoListCore.Properties.CustomErrorCodes", typeof(CustomErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет элемента с таким id.
        /// </summary>
        public static string _700 {
            get {
                return ResourceManager.GetString("700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана модель.
        /// </summary>
        public static string _701 {
            get {
                return ResourceManager.GetString("701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана организация.
        /// </summary>
        public static string _702 {
            get {
                return ResourceManager.GetString("702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация уже имеет приоритет с таким названием.
        /// </summary>
        public static string _703 {
            get {
                return ResourceManager.GetString("703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое название.
        /// </summary>
        public static string _704 {
            get {
                return ResourceManager.GetString("704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть ссылка на этот объект. Нет возможности удалить объект.
        /// </summary>
        public static string _705 {
            get {
                return ResourceManager.GetString("705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет пользователя с таким id.
        /// </summary>
        public static string _706 {
            get {
                return ResourceManager.GetString("706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет приоритета с таким id.
        /// </summary>
        public static string _707 {
            get {
                return ResourceManager.GetString("707", resourceCulture);
            }
        }
    }
}
